---
title: "R Notebook"
output: html_notebook
---

# 0. Prepare environment

Load necessary packages and import functions.

```{r}
# Data import
library(googledrive)
library(readxl)
#library(phyloseq)


# All data format modifications and filtering and plotting
library(tidyverse)
'%!in%' <- function(x,y)!('%in%'(x,y))
source("Code/Functions.R")
library(zoo)

# Statistical tools
library(vegan)

# Specific plotting tools
library(ggpubr)
library(paletteer)
library(viridis)
library(cowplot)
#library(ggnewscale)
source("Code/scales_and_themes.R")

# Make sure tidyverse is the latest loaded package
detach("package:tidyverse", unload=TRUE)
library(tidyverse)
```



# 1. Filter and normalize 18S data


```{r}
seq_depth_plot_18S <- function(data) {
  tmp <- data %>%
    group_by(Library_ID, Sample_type, MiSeq_library) %>% 
    summarise(Library_Size = sum(Abundance)) %>% 
    arrange(Library_Size)
  
  tmp$Index <- seq(nrow(tmp))
  tmp %>% 
    ggplot() +
    geom_point(aes(Index, Library_Size, colour = Sample_type, label = Library_ID))
}
```


```{r}
# Plot ranked sequencing depth with threshold line
All_18S_data_pr2 %>%
  filter(is.na(Fastq_ID) == FALSE) %>%
  filter(Sample_type != "Control") %>% 
  seq_depth_plot() +
  theme_cowplot(12) +
  theme(aspect.ratio = 1,
        strip.background =element_blank()) +
  geom_abline(intercept = 10000, linetype = 4)
ggsave("Figure_output/Sequencing_Depth_18SPR.pdf", width = 7, height = 4.5)

All_18S_data_pr2 %>%
  group_by(Library_ID, Sample_type) %>% 
  summarise()

All_18S_data_pr2
All_18S_data_pr2 %>% 
  pull(Sample_type) %>% unique


# Filter out libraries under threshold line
Good_18S_data_pr2 <- All_18S_data_pr2 %>% 
  group_by(Library_ID) %>%
  filter(Site_ID == "QU39") %>% 
  filter(sum(Abundance)>10000) %>% 
  ungroup()

print("Median 18S library size:")
Good_18S_data_pr2 %>% 
  group_by(Library_ID) %>% 
  summarise(SeqDepth = sum(Abundance)) %>%
  pull(SeqDepth) %>% median

print("Number of final 18S libraries:")
Good_18S_data_pr2 %>% 
  pull(Library_ID) %>% unique %>%  length

```


```{r}
tmp <- Good_18S_data_pr2 %>%
  filter(Sample_type == "DNA",
         Project_name == "QU39",
         Kingdom == "Eukaryota") %>%
  mutate(ASV = paste(MiSeq_library, ASV)) %>% 
  rarefy_sequence_depth(sample = Library_ID, taxa = ASV, abundance = Abundance)
```


## Low taxa - stepwise aggregation
```{r}
Genus_level <- tmp %>%
  filter(Division != "Metazoa") %>% 
  filter(!str_ends(Genus, "@")) %>%
  filter(!str_ends(Genus, "X")) %>% 
  filter(Line_out_depth %in% c(0, 5, 30)) %>% 
  index_RA(Library_ID, Genus, Abundance)

Genus_level %>%
  group_by(Genus) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  ungroup() %>% 
  mutate(Genus = fct_reorder(Genus, RA_Index, .fun = ~ quantile(.x, 0.75), .desc = TRUE)) %>%
  ggplot() +
  geom_boxplot(aes(Genus, RA_Index)) +
  labs(x = "Genus", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_genera <- Genus_level %>%
  group_by(Genus) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Genus) %>% unique()

abundant_genera
```
```{r}
Family_level <- tmp %>%
  filter(Genus %!in% abundant_genera) %>% 
  filter(Division != "Metazoa") %>% 
  filter(!str_ends(Family, "@")) %>%
  filter(!str_ends(Family, "X")) %>%
  filter(Line_out_depth %in% c(0, 5, 30)) %>% 
  index_RA(Library_ID, Family, Abundance)

Family_level %>%
  group_by(Family) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  ungroup() %>% 
  mutate(Family = fct_reorder(Family, RA_Index, .fun = ~ quantile(.x, 0.75), .desc = TRUE)) %>%
  ggplot() +
  geom_boxplot(aes(Family, RA_Index)) +
  labs(x = "Family", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_families <- Family_level %>%
  group_by(Family) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Family) %>% unique()

abundant_families
```

```{r}
Order_level <- tmp %>%
  filter(Genus %!in% abundant_genera) %>%
  filter(Family %!in% abundant_families) %>%
  filter(Division != "Metazoa") %>% 
  filter(!str_ends(Order, "@")) %>%
  filter(!str_ends(Order, "X")) %>%
  filter(Line_out_depth %in% c(0, 5, 30)) %>% 
  index_RA(Library_ID, Order, Abundance)

Order_level %>%
  group_by(Order) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  ungroup() %>% 
  mutate(Order = fct_reorder(Order, RA_Index, .fun = ~ quantile(.x, 0.75), .desc = TRUE)) %>%
  ggplot() +
  geom_boxplot(aes(Order, RA_Index)) +
  labs(x = "Order", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_orders <- Order_level %>%
  group_by(Order) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Order) %>% unique()

abundant_orders

```
```{r}
Class_level <- tmp %>%
  filter(Genus %!in% abundant_genera) %>%
  filter(Family %!in% abundant_families) %>%
  filter(Order %!in% abundant_orders) %>%
  filter(Division != "Metazoa") %>% 
  filter(!str_ends(Class, "@")) %>%
  filter(!str_ends(Class, "X")) %>%
  filter(Line_out_depth %in% c(0, 5, 30)) %>% 
  index_RA(Library_ID, Class, Abundance)

Class_level %>%
  group_by(Class) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  ungroup() %>% 
  mutate(Class = fct_reorder(Class, RA_Index, .fun = ~ quantile(.x, 0.75), .desc = TRUE)) %>%
  ggplot() +
  geom_boxplot(aes(Class, RA_Index)) +
  labs(x = "Class", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_classes <- Class_level %>%
  group_by(Class) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Class) %>% unique()

abundant_classes

```
```{r}
Division_level <- tmp %>%
  filter(Genus %!in% abundant_genera) %>%
  filter(Family %!in% abundant_families) %>%
  filter(Order %!in% abundant_orders) %>%
  filter(Class %!in% abundant_classes) %>%
  filter(Division != "Metazoa") %>% 
  filter(!str_ends(Division, "@")) %>%
  filter(!str_ends(Division, "X")) %>%
  filter(Line_out_depth %in% c(0, 5, 30)) %>% 
  index_RA(Library_ID, Division, Abundance)

Division_level %>%
  group_by(Division) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  ungroup() %>% 
  mutate(Division = fct_reorder(Division, RA_Index, .fun = ~ quantile(.x, 0.75), .desc = TRUE)) %>%
  ggplot() +
  geom_boxplot(aes(Division, RA_Index)) +
  labs(x = "Division", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_divisions <- Division_level %>%
  group_by(Division) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Division) %>% unique()

abundant_divisions
```


```{r}
Genus <- tmp %>% 
  filter(Genus %in% abundant_genera) %>% 
  group_by(Library_ID, Taxa = Genus) %>% 
  summarise(Abundance = sum(Abundance),
            Level = "Genus",
            Hakai_ID, Sample_date, Line_out_depth,
            Division, Class, Order, Family, Genus)

Family <- tmp %>% 
  filter(Family %in% abundant_families) %>% 
  group_by(Library_ID, Taxa = Family) %>%
  summarise(Abundance = sum(Abundance),
            Level = "Family",
            Hakai_ID, Sample_date, Line_out_depth,
            Division, Class, Order, Family, Genus = NULL)

Order <- tmp %>% 
  filter(Order %in% abundant_orders) %>% 
  group_by(Library_ID, Taxa = Order) %>%
  summarise(Abundance = sum(Abundance),
            Level = "Order",
            Hakai_ID, Sample_date, Line_out_depth,
            Division, Class, Order, Family = NULL, Genus = NULL)

Class <- tmp %>% 
  filter(Class %in% abundant_classes) %>% 
  group_by(Library_ID, Taxa = Class) %>%
  summarise(Abundance = sum(Abundance),
            Level = "Class",
            Hakai_ID, Sample_date, Line_out_depth,
            Division, Class, Order = NULL, Family = NULL, Genus = NULL)

Division <- tmp %>% 
  filter(Division %in% abundant_divisions) %>% 
  group_by(Library_ID, Taxa = Division) %>%
  summarise(Abundance = sum(Abundance),
            Level = "Division",
            Hakai_ID, Sample_date, Line_out_depth,
            Division, Class = NULL, Order = NULL, Family = NULL, Genus = NULL)

pr2_18S_glomm <- bind_rows(Genus,
                           Family,
                           Order,
                           Class,
                           Division)

pr2_18S_glomm_indexed <- pr2_18S_glomm %>%
  index_RA(Library_ID, Taxa, Abundance) %>% 
  left_join(select(pr2_18S_glomm, !Abundance), by = c("Library_ID", "Taxa"))

pr2_18S_glomm_indexed

```


# Plotting functional groups


```{r}
# Phytoplankton - primary producers, including various autotrophic groups
phytoplankton <- c("Aureococcus", "Bathycoccus", "Biecheleria", "Cerataulina", 
                   "Chaetoceros", "Chrysophyceae", "Coscinodiscus", "Dicrateria",
                   "Dictyocha", "Ditylum", "Gymnodinium", "Guinardia", 
                   "Hemiselmis", "Heterocapsa", "Karlodinium", "Micromonas", 
                   "Minidiscus", "Navicula", "Noctilucophyceae", "Ostreococcus", 
                   "Phaeocystis", "Picochlorum", "Prorocentrum", "Pseudo-nitzschia", 
                   "Rhizosolenia", "Skeletonema", "Teleaulax", "Thalassiosira", 
                   "Triparma")

# Zooplankton - primarily heterotrophic protists and small animals
zooplankton <- c("Acantharea_3b", "Askenasia", "Choreotrichida", "Didiniidae",
                 "Laboea", "Leegaardiella", "Litostomatea", "Pelagostrobilidium", 
                 "Protoperidinium", "Rimostrombidium_A", "Strobilidiidae_A", 
                 "Strobilidiidae_I", "Strombidiida", "Strombidiidae", "Tintinnida", 
                 "Tintinnidae", "Tontoniidae_B")

# Heterotrophic Flagellates - often bacterivores or part of microbial loops
heterotrophic_flagellates <- c("Cryothecomonas", "Paraphysomonas", "Picomonas", 
                               "Telonemia-Group-1", "Telonemia-Group-2")

# Mixotrophs - capable of both autotrophic and heterotrophic feeding modes
mixotrophs <- c("Chrysochromulina", "Haptolina", "Haptophyta", "Haptophyta_Clade_HAP3", 
                "Prymnesiales", "Prymnesiophyceae", "Prymnesium")

# Parasitic Protists - species known primarily as parasites or pathogens
parasitic_protists <- c("Hematodinium", "Syndinium", "Thalassomyces")

# Microbial or fungal-like protists - not traditional phytoplankton or zooplankton, often decomposers
microbial_fungi <- c("Aplanochytrium", "Cryptomycota", "Fungi", "Labyrinthulomycetes", 
                     "Oomycota", "Pucciniomycotina", "Thraustochytriaceae")
```

```{r}
pr2_18S_glomm_indexed  %>% 
  filter(Taxa %in% phytoplankton,
         Line_out_depth == 0,
         year(Sample_date) != 2019,
         Level != "Division") %>% 
  ggplot() +
  geom_line(aes(Sample_date, RA_Index, colour = Division)) +
  facet_wrap(~Taxa)


pr2_18S_glomm_indexed  %>% 
  filter(Taxa %in% mixotrophs,
         Line_out_depth == 0,
         year(Sample_date) != 2019,
         Level != "Division") %>% 
  ggplot() +
  geom_line(aes(Sample_date, RA_Index, colour = Division)) +
  facet_wrap(~Taxa)



pr2_18S_glomm_indexed  %>% 
  filter(Taxa %in% c(zooplankton, heterotrophic_flagellates),
         Line_out_depth == 0,
         year(Sample_date) != 2019,
         Level != "Division") %>% 
  ggplot() +
  geom_line(aes(Sample_date, RA_Index, colour = Division)) +
  facet_wrap(~Taxa)

pr2_18S_glomm_indexed  %>% 
  filter(Taxa %in% parasitic_protists,
         Line_out_depth == 0,
         year(Sample_date) != 2019,
         Level != "Division") %>% 
  ggplot() +
  geom_line(aes(Sample_date, RA_Index, colour = Division)) +
  facet_wrap(~Taxa)

pr2_18S_glomm_indexed  %>% 
  filter(Taxa %in% microbial_fungi,
         Line_out_depth == 0,
         year(Sample_date) != 2019,
         Level != "Division") %>% 
  ggplot() +
  geom_line(aes(Sample_date, RA_Index, colour = Division)) +
  facet_wrap(~Taxa)
```





## Plot some importan PP genera
```{r}
tmp1 <- tmp %>% 
  filter(Genus %in% c(
    "Thalassiosira",
    "Skeletonema",
    "Chaetoceros",
    "Ditylum",
    "Ceratium",
    "Protoperidinium",
    "Alexandrium",
    "Micromonas",
    "Bathycoccus",
    "Rhodomonas",
    "Phaeocystis",
    "Pseudo-nitzschia"
  )) %>%
  filter(Line_out_depth == 0,
         year(Sample_date) %in% c(2016, 2017, 2018)) %>%
  index_RA(Library_ID, Genus, abundance = Abundance,
           Sample_date)

tmp1  %>% 
  ggplot() +
  geom_line(aes(Sample_date, RA_Index)) +
  facet_wrap(~Genus)

  mutate(Date = factor(Sample_date)) %>% 
  ggplot() +
  #geom_bar(aes(Date, RA_Index, fill = Genus), stat = "identity", position = "fill") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

plotly::ggplotly(p)

tmp
  
```





```{r}
tmp <- Indexed_18S_pr2 <- Good_18S_data_pr2 %>%
    filter(Sample_type == "DNA",
         Project_name == "QU39") %>% 
  index_RA(sample = Library_ID, taxa = Class, abundance = Abundance,
           Sample_date, Site_ID, Project_name, Line_out_depth, Sample_type)

tmp




Indexed_18S_pr2 %>% 
  pull(Class) %>%  unique()
```


```{r}
Indexed_18S_pr2 %>% 
  filter(Class == "Bacillariophyta") %>% 
      mutate(Depth = factor(Line_out_depth, levels = c(
        250, 100, 30, 5, 0 ))) %>% 
      ggplot() +
      geom_point(aes(Sample_date, Depth, fill = RA_Index))
      
```



```{r}
pr2_18S_glomm_indexed
saveRDS(pr2_18S_glomm_indexed, file = "Data_output/pr2_18S_glomm_indexed.rds")
```


# Same but for COI

```{r}
# Get list of Straig of Georgia zooplankton taxa. 
Taxa_MIC <- df_count_2017 %>%
  filter(Abundance > 0) %>%
  group_by(Genus, Tax1) %>% 
  summarise(Abundance = sum(Abundance)) %>% 
  mutate(Species = ifelse(Tax1 == "*sp.", paste(Genus, "sp.", sep = " "), paste(Genus, Tax1, sep = " "))) %>%
  mutate(Level = ifelse(Tax1 == "*sp.", "Genus", "Species")) %>% 
  pull(Genus) %>% unique()

COI_filtered_df <- Good_COI_data %>%
   filter(Project_name == "QU39",
         year(Sample_date) %in% c(2017)) %>%
    filter(Sample_type == "eDNA",
         Kingdom == "Animalia") %>%
  filter(Genus %in% Taxa_MIC) %>% 
  filter(is.na(Abundance) == FALSE) %>%
  mutate(ASV = paste(ASV, MiSeq_run)) %>% 
  group_by(Library_ID, Hakai_ID, Line_out_depth, Sample_date, Project_name,
           ASV, Species, Genus, Family, Order, Class, Phylum) %>% 
  summarise(Abundance = sum(Abundance))
```

```{r}
get_taxa <- function(data, Taxa, IQR_cutoff = 0.01) {
  
  filt_dat <- data %>%
  filter(!str_ends({{Taxa}}, "@")) %>%
  filter(!str_ends({{Taxa}}, "X")) %>% 
  filter(Line_out_depth %in% c(0, 5, 30, 100)) %>%
  filter(Abundance > 0) %>%
  index_RA(Library_ID, {{Taxa}}, Abundance)


p <- filt_dat %>%
  group_by(Species) %>%
  mutate(IQR = IQR(RA_Index)) %>%
  filter(IQR(RA_Index) > IQR_cutoff) %>% # Calculate IQR for each species
  ungroup() %>%
  mutate(Tax_1 = fct_reorder({{Taxa}}, IQR, .desc = TRUE)) %>%  # Reorder by IQR
  ggplot(aes(Tax_1, RA_Index)) +
  geom_boxplot() +
  labs(x = as_name(ensym(Taxa)), y = "eDNA-index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_taxa <- filt_dat %>%
  group_by({{Taxa}}) %>%
  filter(IQR(RA_Index) > IQR_cutoff) %>% # Adjust 0.5 to your desired IQR threshold
  pull({{Taxa}}) %>% unique()

print(p)
return(abundant_taxa)
  
}

get_taxa(tmp, Species, IQR_cutoff = 0.01)
```


```{r}
Species_level <- tmp %>%
  filter(!str_ends(Species, "@")) %>%
  filter(!str_ends(Species, "X")) %>% 
  filter(Line_out_depth %in% c(0, 5, 30, 100)) %>%
  filter(Abundance > 0) %>%
  index_RA(Library_ID, Species, Abundance)


Species_level %>%
  group_by(Species) %>%
  mutate(IQR = IQR(RA_Index)) %>%
  filter(IQR(RA_Index) > 0.01) %>% # Calculate IQR for each species
  ungroup() %>%
  mutate(Species = fct_reorder(Species, IQR, .desc = TRUE)) %>%  # Reorder by IQR
  ggplot(aes(Species, RA_Index)) +
  geom_boxplot() +
  labs(x = "Species", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_species <- Species_level %>%
  group_by(Species) %>%
  filter(IQR(RA_Index) > 0.001) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Species) %>% unique()

abundant_species
```


```{r}
Genus_level <- tmp %>%
  filter(!str_ends(Genus, "@")) %>%
  filter(!str_ends(Genus, "X")) %>% 
  filter(Line_out_depth %in% c(0, 5, 30, 100)) %>%
  filter(Species %!in% abundant_species) %>% 
  index_RA(Library_ID, Genus, Abundance)

Genus_level %>%
  group_by(Genus) %>%
  #filter(IQR(RA_Index) > 0.001) %>% # Adjust 0.5 to your desired IQR threshold
  ungroup() %>% 
  mutate(Genus = fct_reorder(Genus, RA_Index, .fun = ~ quantile(.x, 0.75), .desc = TRUE)) %>%
  ggplot() +
  geom_boxplot(aes(Genus, RA_Index)) +
  labs(x = "Genus", y = "RA Index") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


abundant_genera <- Genus_level %>%
  group_by(Genus) %>%
  #filter(IQR(RA_Index) > 0.01) %>% # Adjust 0.5 to your desired IQR threshold
  pull(Genus) %>% unique()

abundant_genera
```



```{r}
Species <- tmp %>% 
  filter(Species %in% abundant_species) %>% 
  group_by(Library_ID, Taxa = Species) %>% 
  summarise(Abundance = sum(Abundance),
            Level = "Species",
            Hakai_ID, Sample_date, Line_out_depth,
            Phylum, Class, Order, Family, Genus, Species)



Genus <- tmp %>% 
  filter(Genus %in% abundant_genera) %>% 
  group_by(Library_ID, Taxa = Genus) %>% 
  summarise(Abundance = sum(Abundance),
            Level = "Genus",
            Hakai_ID, Sample_date, Line_out_depth,
            Phylum, Class, Order, Family, Genus)



COI_glom <- bind_rows(Species, Genus)

COI_glom_indexed <- COI_glom %>%
  index_RA(Library_ID, Taxa, Abundance) %>% 
  left_join(select(COI_glom, !Abundance), by = c("Library_ID", "Taxa"))

COI_glom_indexed
```



